'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');const {spawnSync}=require('node:child_process');
const {savedRefs}=require('../hooks/post-tool-save.js');const {recordDecision,observedSaves,lastAuditEvent,auditHealth}=require('../hooks/decision-audit.js');
const sid='00000000-0000-4000-8000-000000000001';const other='00000000-0000-4000-8000-000000000002';
function input(){return {session_id:sid,hook_event_name:'PostToolUse',tool_name:'mcp__priors__remember',tool_input:{body:'never-copy-private'},tool_response:{content:[{type:'text',text:JSON.stringify({operation:'remember',outcome_code:'recorded',resource_ids:[{role:'primary',id:'ZZ-1',version:1}],body:'never-copy-private',search_card:{state:'pending'}})}]}};}
function fixture(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'priors-tool-save-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));return {env:{...process.env,PRIORS_DECISION_AUDIT_FILE:path.join(dir,'audit.jsonl'),PRIORS_PROACTIVE_CANDIDATE_FILE:path.join(dir,'candidates.jsonl')},file:path.join(dir,'audit.jsonl')};}
test('reads only validated recorded resource references, including pending card',()=>{assert.deepEqual(savedRefs(input()),['ZZ-1@1']);const p=input();p.tool_response={operation:'work_event',outcome_code:'recorded',resource_ids:[{role:'primary',id:'ZZ-w2',version:3}]};p.tool_name='mcp__priors__work_event';assert.deepEqual(savedRefs(p),['ZZ-w2@3']);});
test('rejects errors unknown tools operation bad IDs or unbound sessions',()=>{for(const mutate of [p=>p.tool_response.isError=true,p=>p.tool_name='mcp__priors__get',p=>p.session_id=undefined,p=>p.session_id='path/secret',p=>p.tool_response={operation:'remember',outcome_code:'refused',resource_ids:[]},p=>p.tool_response={operation:'remember',outcome_code:'recorded',resource_ids:[{role:'primary',id:'secret',version:1}]}]){const p=input();mutate(p);assert.equal(savedRefs(p),null);}});
test('same-session latest hook turn only, dedup and no last-event end spoof',t=>{const x=fixture(t);recordDecision({decision:'pending',phase:'turn-start',source:'hook',client:'claude',sessionId:sid},x.env);recordDecision({decision:'write-candidate',phase:'tool-save',source:'hook',client:'claude',sessionId:sid,save:{outcome:'recorded',ids:['ZZ-1@1','ZZ-1@1']}},x.env);recordDecision({decision:'write-candidate',phase:'tool-save',source:'hook',client:'claude',sessionId:other,save:{outcome:'recorded',ids:['ZZ-2@1']}},x.env);assert.deepEqual(observedSaves(sid,'claude',x.env),['ZZ-1@1']);assert.equal(lastAuditEvent(x.env).phase,'turn-start');assert.equal(auditHealth(x.env).invalid_lines,0);assert.equal(auditHealth(x.env).pending_turn_starts,1);recordDecision({decision:'pending',phase:'turn-start',source:'hook',client:'claude',sessionId:sid},x.env);assert.throws(()=>observedSaves(sid,'claude',x.env));});
test('CLI auto refs only on explicit recorded write decision; explicit refs still work',t=>{const x=fixture(t);recordDecision({decision:'pending',phase:'turn-start',source:'hook',client:'claude',sessionId:sid},x.env);const hook=spawnSync(process.execPath,[path.join(__dirname,'../hooks/post-tool-save.js')],{input:JSON.stringify(input()),encoding:'utf8',env:x.env});assert.equal(hook.status,0);assert.ok(!fs.readFileSync(x.file,'utf8').includes('never-copy-private'));const args=['--client','claude','--phase','conversation-end','--decision','write-candidate','--save-result','recorded'];const run=a=>spawnSync(process.execPath,[path.join(__dirname,'../hooks/record-decision.js'),...args,...a],{encoding:'utf8',env:x.env});assert.equal(run([]).status,2);const ok=run(['--session-id',sid]);assert.equal(ok.status,0);assert.deepEqual(JSON.parse(ok.stdout).save.ids,['ZZ-1@1']);assert.equal(run(['--saved','ZZ-3@4']).status,0);});
test('over-limit aggregation and malformed stream require manual references',t=>{const x=fixture(t);recordDecision({decision:'pending',phase:'turn-start',source:'hook',client:'claude',sessionId:sid},x.env);for(let i=1;i<=21;i++)recordDecision({decision:'write-candidate',phase:'tool-save',source:'hook',client:'claude',sessionId:sid,save:{outcome:'recorded',ids:['ZZ-'+i+'@1']}},x.env);assert.throws(()=>observedSaves(sid,'claude',x.env));fs.appendFileSync(x.file,'bad');assert.throws(()=>observedSaves(sid,'claude',x.env));});
test('oversized input drains without creating an observation',t=>{const x=fixture(t);const p=input();p.tool_input.body='x'.repeat(2*1024*1024);const r=spawnSync(process.execPath,[path.join(__dirname,'../hooks/post-tool-save.js')],{input:JSON.stringify(p),encoding:'utf8',env:x.env});assert.equal(r.status,0);assert.equal(fs.existsSync(x.file),false);});

test('capture applied matches only recorded items and amend applied requires a version',()=>{const p=input();p.tool_name='mcp__priors__capture';p.tool_response={operation:'capture',outcome_code:'applied',resource_ids:[{role:'primary',id:'ZZ-2',version:1}],items:[{id:'ZZ-2',version:1,outcome_code:'recorded'},{id:'ZZ-3',version:1,outcome_code:'refused'}]};assert.deepEqual(savedRefs(p),['ZZ-2@1']);p.tool_response.items[0].outcome_code='refused';assert.equal(savedRefs(p),null);p.tool_name='mcp__priors__amend';p.tool_response={operation:'amend.revise',outcome_code:'applied',resource_ids:[{role:'primary',id:'ZZ-2',version:2}]};assert.deepEqual(savedRefs(p),['ZZ-2@2']);delete p.tool_response.resource_ids[0].version;assert.equal(savedRefs(p),null);});

test('single text-block array preserves existing response validation',()=>{const p=input();p.tool_response=p.tool_response.content;assert.deepEqual(savedRefs(p),['ZZ-1@1']);p.tool_response.push({type:'text',text:'private-not-a-result'});assert.equal(savedRefs(p),null);p.tool_response=[{type:'text',text:'malformed'}];assert.equal(savedRefs(p),null);p.tool_response=[{type:'image',data:'untrusted'}];assert.equal(savedRefs(p),null);p.tool_response=[{type:'text',text:JSON.stringify({operation:'remember',outcome_code:'refused',resource_ids:[{role:'primary',id:'ZZ-1',version:1}]})}];assert.equal(savedRefs(p),null);});
